// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJc---EC1rnWmga3_ywCZ3Km41Xb4Bjlg',
    appId: '1:27800772734:web:7070f81f653892539af82f',
    messagingSenderId: '27800772734',
    projectId: 'mmaflutterpipelinegithub',
    authDomain: 'mmaflutterpipelinegithub.firebaseapp.com',
    storageBucket: 'mmaflutterpipelinegithub.firebasestorage.app',
    measurementId: 'G-6ZBP6DC71B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5YC9z3CT6GaCSUD52mN3GcVhCgkwlf4I',
    appId: '1:27800772734:android:41ca99d4c256e6059af82f',
    messagingSenderId: '27800772734',
    projectId: 'mmaflutterpipelinegithub',
    storageBucket: 'mmaflutterpipelinegithub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfd0B7t17KPEdLLLeAnWhGPGtuwkl4fLg',
    appId: '1:27800772734:ios:979aae2741dd670d9af82f',
    messagingSenderId: '27800772734',
    projectId: 'mmaflutterpipelinegithub',
    storageBucket: 'mmaflutterpipelinegithub.firebasestorage.app',
    iosBundleId: 'com.example.mmaFlutterPipelinePoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfd0B7t17KPEdLLLeAnWhGPGtuwkl4fLg',
    appId: '1:27800772734:ios:979aae2741dd670d9af82f',
    messagingSenderId: '27800772734',
    projectId: 'mmaflutterpipelinegithub',
    storageBucket: 'mmaflutterpipelinegithub.firebasestorage.app',
    iosBundleId: 'com.example.mmaFlutterPipelinePoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJc---EC1rnWmga3_ywCZ3Km41Xb4Bjlg',
    appId: '1:27800772734:web:5e34a230dfaeab589af82f',
    messagingSenderId: '27800772734',
    projectId: 'mmaflutterpipelinegithub',
    authDomain: 'mmaflutterpipelinegithub.firebaseapp.com',
    storageBucket: 'mmaflutterpipelinegithub.firebasestorage.app',
    measurementId: 'G-9ZX79N0WJ7',
  );
}
